USE ROLE SECURITYADMIN;

CREATE OR REPLACE ROLE WEATHER_ADMIN;
CREATE OR REPLACE ROLE WEATHER_ENGINEER;
CREATE OR REPLACE ROLE WEATHER_ANALYST;
CREATE OR REPLACE ROLE WEATHER_VIEWER;

GRANT ROLE WEATHER_ENGINEER TO ROLE WEATHER_ADMIN;
GRANT ROLE WEATHER_ANALYST TO ROLE WEATHER_ADMIN;
GRANT ROLE WEATHER_VIEWER TO ROLE WEATHER_ANALYST;

GRANT USAGE ON WAREHOUSE WH_WEATHER TO ROLE WEATHER_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_WEATHER TO ROLE WEATHER_ANALYST;

GRANT USAGE ON DATABASE WEATHER_DW TO ROLE WEATHER_ENGINEER;
GRANT USAGE ON SCHEMA WEATHER_DW.RAW TO ROLE WEATHER_ENGINEER;
GRANT USAGE ON SCHEMA WEATHER_DW.CURATED TO ROLE WEATHER_ENGINEER;
GRANT USAGE ON SCHEMA WEATHER_DW.ANALYTICS TO ROLE WEATHER_ANALYST;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA WEATHER_DW.RAW TO ROLE WEATHER_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA WEATHER_DW.CURATED TO ROLE WEATHER_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA WEATHER_DW.ANALYTICS TO ROLE WEATHER_VIEWER;
