USE ROLE SECURITYADMIN;
USE DATABASE WEATHER_DW;
USE SCHEMA CURATED;

CREATE OR REPLACE MASKING POLICY mask_precise_coordinates AS
  (val FLOAT) RETURNS FLOAT ->
  CASE
    WHEN CURRENT_ROLE() IN ('WEATHER_ADMIN', 'WEATHER_ENGINEER') THEN val
    ELSE ROUND(val, 1)
  END;

ALTER TABLE dim_location
MODIFY COLUMN latitude SET MASKING POLICY mask_precise_coordinates;

ALTER TABLE dim_location
MODIFY COLUMN longitude SET MASKING POLICY mask_precise_coordinates;

CREATE OR REPLACE ROW ACCESS POLICY us_only_policy AS
  (country STRING) RETURNS BOOLEAN ->
  CASE
    WHEN CURRENT_ROLE() IN ('WEATHER_ADMIN', 'WEATHER_ENGINEER') THEN TRUE
    WHEN CURRENT_ROLE() = 'WEATHER_ANALYST' AND country = 'United States' THEN TRUE
    ELSE FALSE
  END;

ALTER TABLE dim_location
ADD ROW ACCESS POLICY us_only_policy ON (country);
