CREATE OR REPLACE WAREHOUSE WH_WEATHER
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE WEATHER_DW;
CREATE OR REPLACE SCHEMA WEATHER_DW.RAW;
CREATE OR REPLACE SCHEMA WEATHER_DW.CURATED;
CREATE OR REPLACE SCHEMA WEATHER_DW.ANALYTICS;

USE WAREHOUSE WH_WEATHER;
USE DATABASE WEATHER_DW;
